<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_PassengerCount</name>
   <tag></tag>
   <elementGuidId>7b4966f0-bf3d-4289-a77a-aba874e8a13b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/div/div[1]/div[1]/div[4]/div/h5/span[1]/span</value>
   </webElementProperties>
</WebElementEntity>
