<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_PTripsCount</name>
   <tag></tag>
   <elementGuidId>bdfd0f11-620d-4ddc-b42a-431191156029</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/div/div[1]/div[1]/div[5]/div/h5/span[1]/span</value>
   </webElementProperties>
</WebElementEntity>
