<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NTPA_DueAmount</name>
   <tag></tag>
   <elementGuidId>ad73a08a-6889-4439-88f0-3888ff47d5d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/div/div[1]/div[1]/div[7]/div/div[1]</value>
   </webElementProperties>
</WebElementEntity>
