<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tbl_payTrans</name>
   <tag></tag>
   <elementGuidId>11140941-ce87-412b-85e3-cbf81420a14e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div[3]/div/div[1]/div[2]/div[2]/div/div/div[2]/table/tbody[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div[3]/div/div[1]/div[2]/div[2]/div/div/div[2]/table/tbody[2]</value>
   </webElementProperties>
</WebElementEntity>
